export type CategorieJeu = "arcade" | "reflexion" | "aventure" | "creation" | "sport" | "plateforme";

export interface JeuCatalog {
  id: string;
  nom: string;
  emoji: string;
  description: string;
  categorieLabel: string;
  categorie: CategorieJeu;
  ageMin: number;
  ageMax: number;
  xpCout: number;        // XP pour jouer une session
  minutesSession: number;
  composant: string;
  disponible: boolean;
  difficulte: "facile" | "moyen" | "difficile";
  nouveaute?: boolean;
  populaire?: boolean;
}

export const JEUX_CATALOG: JeuCatalog[] = [
  // ── ARCADE CLASSIQUES ─────────────────────────────────────────────────────
  {
    id: "serpent",
    nom: "Serpent 🐍",
    emoji: "🐍",
    description: "Le classique ! Dirige le serpent, mange les pommes, grandis sans te mordre la queue. Bats ton record !",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 18,
    xpCout: 60, minutesSession: 10,
    composant: "JeuSerpent",
    disponible: true, difficulte: "moyen", populaire: true,
  },
  {
    id: "tetris",
    nom: "Tétris 🟥",
    emoji: "🟥",
    description: "Fais tomber les pièces et complète les lignes ! Plus ça monte, plus c'est intense. Le jeu le plus addictif du monde.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 8, ageMax: 18,
    xpCout: 70, minutesSession: 12,
    composant: "JeuTetris",
    disponible: true, difficulte: "moyen", populaire: true, nouveaute: true,
  },
  {
    id: "dino_saut",
    nom: "Dino Saut 🦕",
    emoji: "🦕",
    description: "Fais sauter le dinosaure par-dessus les cactus et les ptérodactyles ! Jusqu'où peux-tu aller ?",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 6, ageMax: 14,
    xpCout: 40, minutesSession: 8,
    composant: "JeuDino",
    disponible: true, difficulte: "facile", populaire: true, nouveaute: true,
  },
  {
    id: "flappy",
    nom: "Flappy Oiseau 🐦",
    emoji: "🐦",
    description: "Tape pour voler entre les tuyaux ! Un jeu simple mais terriblement difficile à maîtriser.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 18,
    xpCout: 50, minutesSession: 8,
    composant: "JeuFlappy",
    disponible: true, difficulte: "difficile", populaire: true,
  },
  {
    id: "space_invaders",
    nom: "Space Invaders 👾",
    emoji: "👾",
    description: "Des aliens envahissent l'espace ! Déplace ton vaisseau et tire pour les détruire avant qu'ils n'atteignent le sol.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 8, ageMax: 18,
    xpCout: 70, minutesSession: 12,
    composant: "JeuSpaceInvaders",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "asteroides",
    nom: "Astéroïdes 🚀",
    emoji: "🚀",
    description: "Pilote ton vaisseau et détruis les astéroïdes avant qu'ils te percutent ! Attention aux débris.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 9, ageMax: 18,
    xpCout: 70, minutesSession: 12,
    composant: "JeuAsteroides",
    disponible: true, difficulte: "moyen",
  },
  {
    id: "fruit_ninja",
    nom: "Fruit Ninja 🍉",
    emoji: "🍉",
    description: "Tranche les fruits qui volent dans les airs avec ton sabre ! Évite les bombes pour survivre.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 6, ageMax: 14,
    xpCout: 50, minutesSession: 8,
    composant: "JeuFruitNinja",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "casse_briques",
    nom: "Casse-Briques 🧱",
    emoji: "🧱",
    description: "Renvoie la balle avec ta raquette pour briser toutes les briques. Débloques des power-ups secrets !",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 18,
    xpCout: 60, minutesSession: 12,
    composant: "JeuCasseBriques",
    disponible: true, difficulte: "moyen",
  },
  {
    id: "pac_dot",
    nom: "Pac-Dot 🟡",
    emoji: "🟡",
    description: "Mange tous les points du labyrinthe sans te faire attraper par les fantômes ! Un classique intemporel.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 18,
    xpCout: 70, minutesSession: 12,
    composant: "JeuPacDot",
    disponible: true, difficulte: "moyen", populaire: true,
  },
  {
    id: "pong",
    nom: "Pong ⚪",
    emoji: "⚪",
    description: "Le premier jeu vidéo de l'histoire ! Renvoie la balle avec ta raquette et marque des points contre l'IA.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 6, ageMax: 18,
    xpCout: 40, minutesSession: 8,
    composant: "JeuPong",
    disponible: true, difficulte: "facile",
  },

  // ── RÉFLEXION ─────────────────────────────────────────────────────────────
  {
    id: "jeu_2048",
    nom: "2048 🔢",
    emoji: "🔢",
    description: "Fusionne les carreaux identiques pour atteindre 2048 ! Simple à comprendre, presque impossible à maîtriser.",
    categorieLabel: "Réflexion",
    categorie: "reflexion",
    ageMin: 9, ageMax: 18,
    xpCout: 60, minutesSession: 12,
    composant: "Jeu2048",
    disponible: true, difficulte: "moyen", populaire: true, nouveaute: true,
  },
  {
    id: "memoire_emoji",
    nom: "Mémoire Émojis 🃏",
    emoji: "🃏",
    description: "Retourne les cartes et trouve toutes les paires d'emojis ! Plus de paires = plus difficile.",
    categorieLabel: "Mémoire",
    categorie: "reflexion",
    ageMin: 6, ageMax: 12,
    xpCout: 40, minutesSession: 8,
    composant: "JeuMemoire",
    disponible: true, difficulte: "facile", populaire: true,
  },
  {
    id: "memoire_avance",
    nom: "Mémoire Champion 🧠",
    emoji: "🧠",
    description: "20 paires à trouver ! Le vrai test de ta mémoire. Bats le chrono et deviens le champion.",
    categorieLabel: "Mémoire",
    categorie: "reflexion",
    ageMin: 10, ageMax: 18,
    xpCout: 60, minutesSession: 10,
    composant: "JeuMemoire",
    disponible: true, difficulte: "difficile",
  },
  {
    id: "puzzle_glissant",
    nom: "Puzzle Glissant 🧩",
    emoji: "🧩",
    description: "Glisse les pièces pour reconstituer l'image. 8 pièces pour commencer, puis 15 pour les experts !",
    categorieLabel: "Puzzle",
    categorie: "reflexion",
    ageMin: 8, ageMax: 16,
    xpCout: 60, minutesSession: 12,
    composant: "JeuPuzzleGlissant",
    disponible: true, difficulte: "moyen",
  },
  {
    id: "pendu",
    nom: "Le Pendu 🎯",
    emoji: "🎯",
    description: "Devine le mot mystère lettre par lettre avant que le bonhomme soit pendu ! Thèmes variés et amusants.",
    categorieLabel: "Mots",
    categorie: "reflexion",
    ageMin: 8, ageMax: 18,
    xpCout: 50, minutesSession: 10,
    composant: "JeuPendu",
    disponible: true, difficulte: "moyen",
  },
  {
    id: "minesweeper",
    nom: "Démineur 💣",
    emoji: "💣",
    description: "Révèle les cases sans exploser sur une mine ! Utilise la logique pour déduire où sont les bombes.",
    categorieLabel: "Logique",
    categorie: "reflexion",
    ageMin: 10, ageMax: 18,
    xpCout: 70, minutesSession: 15,
    composant: "JeuDemineur",
    disponible: true, difficulte: "difficile",
  },
  {
    id: "tower_defense",
    nom: "Tour de Défense 🏰",
    emoji: "🏰",
    description: "Place tes tours pour stopper les envahisseurs ! Gagne de l'or, améliore tes tours et survive aux vagues.",
    categorieLabel: "Stratégie",
    categorie: "reflexion",
    ageMin: 10, ageMax: 18,
    xpCout: 90, minutesSession: 20,
    composant: "JeuTowerDefense",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "pixel_art",
    nom: "Pixel Art 🎨",
    emoji: "🎨",
    description: "Crée des œuvres pixel par pixel avec ta palette de couleurs ! Exprime ta créativité sans limite.",
    categorieLabel: "Créativité",
    categorie: "creation",
    ageMin: 6, ageMax: 18,
    xpCout: 80, minutesSession: 20,
    composant: "JeuPixelArt",
    disponible: true, difficulte: "facile", populaire: true,
  },

  // ── SPORT & COURSE ────────────────────────────────────────────────────────
  {
    id: "ski_slalom",
    nom: "Ski Slalom ⛷️",
    emoji: "⛷️",
    description: "Descends la pente en slalom entre les portes ! Plus tu vas vite, plus les obstacles arrivent rapidement.",
    categorieLabel: "Sport",
    categorie: "sport",
    ageMin: 7, ageMax: 16,
    xpCout: 50, minutesSession: 8,
    composant: "JeuSkiSlalom",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "course_infinie",
    nom: "Course Infinie 🏃",
    emoji: "🏃",
    description: "Cours à l'infini en changeant de voie ! Collecte des pièces et évite les obstacles.",
    categorieLabel: "Course",
    categorie: "plateforme",
    ageMin: 7, ageMax: 14,
    xpCout: 50, minutesSession: 8,
    composant: "JeuCourseInfinie",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "basketball_shoot",
    nom: "Basketball Shoot 🏀",
    emoji: "🏀",
    description: "Lance le ballon dans le panier ! Ajuste la force et l'angle pour marquer le maximum de paniers.",
    categorieLabel: "Sport",
    categorie: "sport",
    ageMin: 7, ageMax: 16,
    xpCout: 50, minutesSession: 8,
    composant: "JeuBasketball",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "soccer_penaltys",
    nom: "Pénaltys ⚽",
    emoji: "⚽",
    description: "Tire les pénaltys en choisissant ta direction ! Puis joue le gardien pour arrêter les tirs adverses.",
    categorieLabel: "Sport",
    categorie: "sport",
    ageMin: 7, ageMax: 16,
    xpCout: 50, minutesSession: 8,
    composant: "JeuSoccerPenaltys",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "hockey_tir",
    nom: "Tir au But 🏒",
    emoji: "🏒",
    description: "Tire la rondelle dans le filet ! Déjoue le gardien avec les bons angles. On est au Québec !",
    categorieLabel: "Sport",
    categorie: "sport",
    ageMin: 7, ageMax: 16,
    xpCout: 50, minutesSession: 8,
    composant: "JeuHockeyTir",
    disponible: true, difficulte: "facile", nouveaute: true,
  },

  // ── PLATEFORME & AVENTURE ─────────────────────────────────────────────────
  {
    id: "platformer_saut",
    nom: "Super Saut 🦊",
    emoji: "🦊",
    description: "Saute de plateforme en plateforme sans tomber ! Collecte des étoiles et débloques des niveaux secrets.",
    categorieLabel: "Plateforme",
    categorie: "plateforme",
    ageMin: 7, ageMax: 14,
    xpCout: 70, minutesSession: 12,
    composant: "JeuPlatformer",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "donjon_aventure",
    nom: "Donjon Aventure ⚔️",
    emoji: "⚔️",
    description: "Explore le donjon, bats les monstres, trouve le trésor ! Un mini-RPG avec combat au tour par tour.",
    categorieLabel: "Aventure",
    categorie: "aventure",
    ageMin: 10, ageMax: 17,
    xpCout: 90, minutesSession: 20,
    composant: "JeuDonjon",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "labyrinthe",
    nom: "Labyrinthe 🌀",
    emoji: "🌀",
    description: "Trouve la sortie du labyrinthe ! Plus tu avances, plus les labyrinthes deviennent grands et complexes.",
    categorieLabel: "Puzzle",
    categorie: "reflexion",
    ageMin: 7, ageMax: 16,
    xpCout: 50, minutesSession: 10,
    composant: "JeuLabyrinthe",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "construction",
    nom: "Mini Construction 🏗️",
    emoji: "🏗️",
    description: "Empile les blocs au bon moment pour construire la tour la plus haute !",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 14,
    xpCout: 60, minutesSession: 10,
    composant: "JeuConstruction",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "tir_arc",
    nom: "Tir à l'Arc 🏹",
    emoji: "🏹",
    description: "Ajuste la trajectoire de ta flèche et vise la cible ! Le vent change à chaque round.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 8, ageMax: 16,
    xpCout: 60, minutesSession: 10,
    composant: "JeuTirArc",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "cartes_bataille",
    nom: "Bataille de Cartes 🃏",
    emoji: "🃏",
    description: "La carte la plus haute gagne la manche ! Récupère toutes les cartes de l'IA.",
    categorieLabel: "Cartes",
    categorie: "reflexion",
    ageMin: 9, ageMax: 16,
    xpCout: 70, minutesSession: 15,
    composant: "JeuCartesBataille",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "echecs_rapide",
    nom: "Échecs Rapides ♟️",
    emoji: "♟️",
    description: "Partie d'échecs express contre l'IA ! Tu as 5 minutes, l'IA s'adapte à ton niveau. Mat en 3 ?",
    categorieLabel: "Stratégie",
    categorie: "reflexion",
    ageMin: 11, ageMax: 18,
    xpCout: 90, minutesSession: 15,
    composant: "JeuEchecs",
    disponible: true, difficulte: "difficile", nouveaute: true,
  },
  {
    id: "cuisinier_fou",
    nom: "Cuisinier Fou 🍳",
    emoji: "🍳",
    description: "Attrape les bons ingrédients avec ton assiette pour compléter les recettes !",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 14,
    xpCout: 60, minutesSession: 10,
    composant: "JeuCuisinier",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "jetpack",
    nom: "Jetpack Aventure 🚀",
    emoji: "🚀",
    description: "Maintiens le bouton pour voler ! Passe entre les obstacles avec ton jetpack.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 8, ageMax: 16,
    xpCout: 60, minutesSession: 10,
    composant: "JeuJetpack",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "bille_rebond",
    nom: "Bille Rebondissante 🔮",
    emoji: "🔮",
    description: "Fais rebondir la bille pour casser toutes les briques ! Multi-niveaux avec briques résistantes.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 8, ageMax: 16,
    xpCout: 60, minutesSession: 10,
    composant: "JeuBilleRebond",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "gomoku",
    nom: "Gomoku 5 en ligne ⚫",
    emoji: "⚫",
    description: "Aligne 5 pierres de ta couleur avant l'IA ! Développe ton sens stratégique.",
    categorieLabel: "Stratégie",
    categorie: "reflexion",
    ageMin: 9, ageMax: 18,
    xpCout: 70, minutesSession: 15,
    composant: "JeuGomoku",
    disponible: true, difficulte: "difficile", nouveaute: true,
  },
  {
    id: "puissance4",
    nom: "Puissance 4 🔴",
    emoji: "🔴",
    description: "Aligne 4 jetons de ta couleur — horizontalement, verticalement ou en diagonale ! Bats l'IA.",
    categorieLabel: "Stratégie",
    categorie: "reflexion",
    ageMin: 7, ageMax: 18,
    xpCout: 60, minutesSession: 12,
    composant: "JeuPuissance4",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "paint_libre",
    nom: "Peinture Libre 🖌️",
    emoji: "🖌️",
    description: "Un tableau blanc, des pinceaux, des couleurs infinies ! Crée ce que tu veux. L'art est libre.",
    categorieLabel: "Créativité",
    categorie: "creation",
    ageMin: 6, ageMax: 18,
    xpCout: 60, minutesSession: 20,
    composant: "JeuPaintLibre",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "course_voiture",
    nom: "Course de Voitures 🏎️",
    emoji: "🏎️",
    description: "Conduis ta voiture sur la route, évite les véhicules adverses et collecte les pièces !",
    categorieLabel: "Course",
    categorie: "sport",
    ageMin: 7, ageMax: 16,
    xpCout: 70, minutesSession: 12,
    composant: "JeuCourseVoiture",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "planete_zombie",
    nom: "Zombies 🧟",
    emoji: "🧟",
    description: "Survie ! Déplace-toi et tire automatiquement sur les zombies. Tiens jusqu'à la dernière vague !",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 10, ageMax: 18,
    xpCout: 80, minutesSession: 12,
    composant: "JeuZombie",
    disponible: true, difficulte: "difficile", nouveaute: true,
  },
  {
    id: "ninja_run",
    nom: "Ninja Runner 🥷",
    emoji: "🥷",
    description: "Cours à toute vitesse, saute par-dessus les obstacles et glisse sous les barrières. Tu es un ninja !",
    categorieLabel: "Plateforme",
    categorie: "plateforme",
    ageMin: 7, ageMax: 15,
    xpCout: 50, minutesSession: 8,
    composant: "JeuNinjaRun",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "solitaire",
    nom: "Bataille de Cartes 🃏",
    emoji: "🃏",
    description: "La carte la plus haute remporte la manche ! Gagne toutes les cartes de l'adversaire.",
    categorieLabel: "Cartes",
    categorie: "reflexion",
    ageMin: 9, ageMax: 18,
    xpCout: 70, minutesSession: 15,
    composant: "JeuCartesBataille",
    disponible: true, difficulte: "facile",
  },
  {
    id: "bubble_shooter",
    nom: "Bubble Shooter 🫧",
    emoji: "🫧",
    description: "Tire des bulles de couleur pour en aligner 3 ou plus et les faire éclater ! Vide l'écran pour gagner.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 7, ageMax: 16,
    xpCout: 60, minutesSession: 12,
    composant: "JeuBubbleShooter",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "origami_digital",
    nom: "Origami Digital 🦢",
    emoji: "🦢",
    description: "Plie le papier virtuel selon les instructions pour créer des animaux origami ! Zen et créatif.",
    categorieLabel: "Créativité",
    categorie: "creation",
    ageMin: 8, ageMax: 16,
    xpCout: 70, minutesSession: 15,
    composant: "JeuOrigami",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "galaxie_shooter",
    nom: "Galaxie Shooter 🌌",
    emoji: "🌌",
    description: "Défends la galaxie contre des vagues d'aliens ! Tir automatique, esquive les projectiles ennemis.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 9, ageMax: 17,
    xpCout: 80, minutesSession: 15,
    composant: "JeuGalaxie",
    disponible: true, difficulte: "difficile", nouveaute: true,
  },
  {
    id: "fishing",
    nom: "Pêche Magique 🎣",
    emoji: "🎣",
    description: "Lance ta ligne et attrape le plus gros poisson ! Chaque poisson a sa propre valeur.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 6, ageMax: 14,
    xpCout: 40, minutesSession: 8,
    composant: "JeuFishing",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "simon_says",
    nom: "Simon 🟢🔴🟡🔵",
    emoji: "🎵",
    description: "Mémorise la séquence de couleurs et répète-la ! La séquence s'allonge à chaque bon tour. Jusqu'où ?",
    categorieLabel: "Mémoire",
    categorie: "reflexion",
    ageMin: 6, ageMax: 18,
    xpCout: 40, minutesSession: 8,
    composant: "JeuSimon",
    disponible: true, difficulte: "moyen",
  },
  {
    id: "sokoban",
    nom: "Pousseur de Caisses 📦",
    emoji: "📦",
    description: "Pousse les caisses sur les cases cibles ! Simple à comprendre, impossible à maîtriser.",
    categorieLabel: "Puzzle",
    categorie: "reflexion",
    ageMin: 9, ageMax: 18,
    xpCout: 70, minutesSession: 15,
    composant: "JeuSokoban",
    disponible: true, difficulte: "difficile", nouveaute: true,
  },
  {
    id: "whack_mole",
    nom: "Taupes Folles 🐹",
    emoji: "🐹",
    description: "Les taupes sortent de leurs terriers — tape-les le plus vite possible ! Attention aux taupes en or.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 6, ageMax: 12,
    xpCout: 40, minutesSession: 6,
    composant: "JeuFrappeTaupe",
    disponible: true, difficulte: "facile", populaire: true,
  },
  {
    id: "tetris_blitz",
    nom: "Tetris Blitz ⚡",
    emoji: "⚡",
    description: "Tetris en mode turbo — les pièces tombent très vite ! 2 minutes pour le score le plus élevé.",
    categorieLabel: "Arcade",
    categorie: "arcade",
    ageMin: 10, ageMax: 18,
    xpCout: 80, minutesSession: 8,
    composant: "JeuTetris",
    disponible: true, difficulte: "difficile", nouveaute: true,
  },
  {
    id: "match3",
    nom: "Match 3 Gemmes 💎",
    emoji: "💎",
    description: "Aligne 3 gemmes identiques pour les faire exploser ! Crée des combos pour déclencher des super-explosions.",
    categorieLabel: "Puzzle",
    categorie: "reflexion",
    ageMin: 7, ageMax: 16,
    xpCout: 60, minutesSession: 12,
    composant: "JeuMatch3",
    disponible: true, difficulte: "moyen", populaire: true, nouveaute: true,
  },

  // ── JEUX ÉDUCATIFS ────────────────────────────────────────────────────────
  {
    id: "calcul_mental",
    nom: "Calcul Mental ⚡",
    emoji: "⚡",
    description: "Réponds le plus vite possible aux additions, soustractions, multiplications et divisions ! Combos et chrono.",
    categorieLabel: "Mathématiques",
    categorie: "reflexion",
    ageMin: 7, ageMax: 14,
    xpCout: 50, minutesSession: 10,
    composant: "JeuCalculMental",
    disponible: true, difficulte: "moyen", nouveaute: true, populaire: true,
  },
  {
    id: "multiplication_sprint",
    nom: "Tables Sprint 🔢",
    emoji: "🔢",
    description: "Maîtrise les tables de multiplication de 2 à 12 ! Bats le record de ta série et deviens champion des maths.",
    categorieLabel: "Mathématiques",
    categorie: "reflexion",
    ageMin: 7, ageMax: 12,
    xpCout: 40, minutesSession: 8,
    composant: "JeuMultiplication",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "mots_meles",
    nom: "Mots Mêlés 🔍",
    emoji: "🔍",
    description: "Trouve tous les mots cachés dans la grille ! Glisse pour sélectionner, horizontal, vertical, diagonal.",
    categorieLabel: "Langage",
    categorie: "reflexion",
    ageMin: 8, ageMax: 16,
    xpCout: 50, minutesSession: 12,
    composant: "JeuMotsMeles",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "sudoku_jr",
    nom: "Sudoku Junior 🟦",
    emoji: "🟦",
    description: "Grille 4×4 avec des chiffres colorés ! Chaque chiffre une seule fois par ligne, colonne et carré.",
    categorieLabel: "Logique",
    categorie: "reflexion",
    ageMin: 7, ageMax: 12,
    xpCout: 50, minutesSession: 10,
    composant: "JeuSudokuJr",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "geo_quiz",
    nom: "Géo Quiz 🌍",
    emoji: "🌍",
    description: "Teste ta connaissance de la géographie mondiale ! Capitales, pays, drapeaux et monuments célèbres.",
    categorieLabel: "Géographie",
    categorie: "reflexion",
    ageMin: 9, ageMax: 18,
    xpCout: 50, minutesSession: 10,
    composant: "JeuGeoQuiz",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "fraction_fighter",
    nom: "Fraction Fighter 🥊",
    emoji: "🥊",
    description: "Quelle fraction est la plus grande ? Compare les fractions et gagne des vies ! 3 vies pour survivre.",
    categorieLabel: "Mathématiques",
    categorie: "reflexion",
    ageMin: 9, ageMax: 14,
    xpCout: 50, minutesSession: 8,
    composant: "JeuFractionFighter",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
  {
    id: "tangram_jeu",
    nom: "Tangram 🔷",
    emoji: "🔷",
    description: "Reconnaît la forme dessinée avec les pièces du tangram ! Développe ton sens spatial.",
    categorieLabel: "Logique",
    categorie: "reflexion",
    ageMin: 7, ageMax: 14,
    xpCout: 40, minutesSession: 8,
    composant: "JeuTangram",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "couleur_mix",
    nom: "Mélange de Couleurs 🎨",
    emoji: "🎨",
    description: "Apprends à mélanger les couleurs primaires ! Rouge + Bleu = Violet... Deviens un artiste scientifique.",
    categorieLabel: "Sciences",
    categorie: "reflexion",
    ageMin: 6, ageMax: 12,
    xpCout: 40, minutesSession: 8,
    composant: "JeuCouleurMix",
    disponible: true, difficulte: "facile", nouveaute: true,
  },
  {
    id: "typing_speed",
    nom: "Vitesse de Frappe ⌨️",
    emoji: "⌨️",
    description: "Tape les mots le plus vite possible ! Chronomètre 60 secondes et mesure ta vitesse en mots/min.",
    categorieLabel: "Langage",
    categorie: "reflexion",
    ageMin: 8, ageMax: 18,
    xpCout: 50, minutesSession: 8,
    composant: "JeuTypingSpeed",
    disponible: true, difficulte: "moyen", nouveaute: true,
  },
];

export function getJeuById(id: string): JeuCatalog | null {
  return JEUX_CATALOG.find((j) => j.id === id) ?? null;
}

export function getJeuxDisponibles(): JeuCatalog[] {
  return JEUX_CATALOG.filter((j) => j.disponible);
}

export function getJeuxParAge(age: number): JeuCatalog[] {
  return JEUX_CATALOG.filter((j) => age >= j.ageMin && age <= j.ageMax);
}
